colores = {"rojo", "blanco", "azul"}

colores.add("violeta")
print(colores)
print("*" * 100)
colores.add("dorado")
print(colores)
print("*" * 100)
colores.discard("celeste")
print(colores)
print("*" * 100)
colores.discard("blanco")
print(colores)
print("*" * 100)
colores.discard("dorado")
print(colores)
print("*" * 100)
